### ISSUE TITLE
Claim all button on "Claim Page"  (Possible Back-end)

### ISSUE THREAD

**Issue by Thefox797** [vertekfi/dex-frontend#46]
This was a heavy reqeusted feature on the previous DEX.
Not sure if it should be on the FE page. It's both FE and BE i expect.

**Comment by 0xBriz** [comment]
This isn't possible if I am understanding what you're looking for here. To claim all would simply trigger a list of Metamask transactions for each pool/gauge. Same as clicking the individual claim buttons. Due to how the gauge reward system works. Users have to claim from each individual gauge contract.

**Comment by Thefox797** [comment]
No problem ;) If it can't be done it can't be done.
Was a quality of life improvement which also was high on the wish list for AEQ at the time.
