### ISSUE TITLE
"About this project" minor UX issue

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#87]
Just a small UX thing. Clicking out of the "About this project" modal/overlay, will make that section of the pool page display the "Investments" filter.

- Perhaps move the button to the right a bit to visually separate it from the filters coz its not really a filter header?
- Good job tho, will get the content to u asap

**_Clicking the button brings up the modal/overlay just fine:_**
![image](https://user-images.githubusercontent.com/106936065/218298206-ddcd843b-a65d-45a8-80ab-93ec663b27bf.png)

**_Once the user clicks out, it defaults to displaying as if they clicked the "Investments" filter:_**
![image](https://user-images.githubusercontent.com/106936065/218298318-8d8aadb0-8672-465e-89fb-d9babc7a6f25.png)

**Comment by 0xBriz** [comment]
Ah yeah. I have it set to go back to investments since there is nothing to view once the modal closes. Appears setting the index for the open tab/option updates what is shown but is not updating the styling for the selected option. I will mess with it then or just move it to the side like you mentioned.

**Comment by harleen-m** [comment]
I already tried messing with it but I didn't manage to get it working, I think the tab header is selected based on aria-selected property, but I struggled a bit to change that.

Maybe a better idea would be to introduce a button separate from the tabs. Alternatively what if the About this project content gets displayed in the tab instead of the popup?

**Comment by 0xKang** [comment]
Spoke to jumpman and we are moving the button to elsewhere on the pool page and making it separate from the investment filter tabs.

This way its a button on its own and stands out.

**Comment by 0xKang** [comment]
Resolved.
