### ISSUE TITLE
duplicated Smart order rows

### ISSUE THREAD

**Issue by SweeTouch** [vertekfi/dex-frontend#89]
smart order routing is showing duplicates of the same route
![image](https://user-images.githubusercontent.com/38596528/218318898-1731b189-1163-43ec-ab46-213fa59b2cbd.png)

**Comment by 0xBriz** [comment]
I noticed this the other day and have been looking into it today along with other router updates. Believe a recent update caused the pool hops that are linked up after the router does it's thing to not account for pools already linked up. Saw beets also updated a couple weeks ago due to seeing something similar. I will try to get it sorted out today then.

**Comment by KoenigKeule** [comment]
Just now it did something else being outside the pop-up.
![image](https://user-images.githubusercontent.com/125215836/219104286-91458dc5-4f6b-4195-8c01-7ce42b1ceedf.png)

**Comment by 0xKang** [comment]
tagging @0xBriz  and @jumpman23xx here that this issue has 2 parts:

- S.O.R display glitch. Multiple rows showing.
- Container overflow (even after expanding card to XL size)

**Comment by jumpman23xx** [comment]
glitch cleared
